### ISSUE TITLE
Clarify membership voting process

### ISSUE THREAD

**Issue by MidLifeXis** [Perl5-Alien/Perl5-Alien-Documents#4]
A question came up on #3 whether membership votes should be secret or not.  It appears that the membership part of this needs a little bit of discussion.  I see multiple that should be discussed:
- Membership votes should be private, and votes managed by the Pumpkin.
- What type of guidance should the voting members have when considering membership?

**Comment by zmughal** [comment]
Sorry for interjecting here, but I would like to see more activity with Alien. Perhaps the Apache Software Foundation's [new commiter guide](https://community.apache.org/newcommitter.html) could be helpful for making the decision?

**Comment by MidLifeXis** [comment]
The process outlines in the above Apache guide contains many similarities with the conclusion I was independently coming to.
1. There needs to be a private discussion / vote area, unless the final decision is in the hands of the Pumpkin.
2. There should also be an individual(s) tasked with implementing the final decision.  Administrivia.
3. A nomination does not necessarily mean that an individual accepts.
4. A time limit for discussion should be set.

All I have at this time.

**Comment by plicease** [comment]
I am not sure that any of this bureaucracy is helping this project, which seems to have completely stalled.  I think good things are intended by those in charge, but they do not appear to have the time to devote to this project, and if they care about it they should pass the baton.  @zmughal and @mohawk2 are chomping at the bit to make some progress on this and I'd be interested in collaborating as well, but I am extremely skeptical due to the lack of progress.

After talking to @devel-chm at DCBPW it didn't seem like he was all that interested in being part of the core AB leadership, and was quite skeptical of the usefulness of AB in its current state.  Please forgive me if I am misrepresenting.  I considered some of his complaints when designing the new non-AB version of Alien::Libarchive, which I feel addresses most of the outstanding problems with AB.  It would be fantastic to get those solutions in a general product like AB.

Though not my first choice, I think one alternative for those that care about Alien would be to fork AB under an alternate namespace and start adding features there.

Please prove me wrong.  I would love to be wrong.

**Comment by mohawk2** [comment]
For what it's worth, I agree. I expect Mojolicious is a large project with lots of people involved. The Perl Toolchain Gang doesn't have a voting process with Annual General Meetings, and it seems to do Ok.

Please consider this a plea to "do your business", or get off the potty.

**Comment by devel-chm** [comment]
I see a lot of limitations of the current Alien module approach and
feel that the general scheme of implementation needs to be
improved to work the way I think it should be capable of operating,

http://blogs.perl.org/users/chris_marshall/2013/12/a-framework-for-alien-modules-the-alien2-manifesto.html

I think AB support for Alien2 would be great and thought there might
be a way to steer AB into that capability as a way to accelerate
implementation and acceptance.  Things stalled for me when the
AB hand-off from Joel turned into a meta-development discusion and
organizational group.  Made the more frustrating to me since I think
a move to some of the Alien2 concepts is the _key_ point and not
minor, iterative tweaks to the current unix-centric implementation.

The pieces are there but I think Alien2 needs to be the implementation
goal and not Alien.

To be fair, I guess my Alien2 got "plonked" too with little buy-in
from other developers and a lack of time to pursue on my end.  :-)

I'm happy to participate in AB and Alien2 technical development but
I think some of this bureaucracy could be replaced by a single,
honorable, team lead to steer the development---and to do no harm
as much as possible along the way.

From a win32 and non-unix platform point of view, the continuation
of the current, unix-centric AB is becoming part of the problem and
not the solution if one doesn't happen to have a conveniently unix-ish
perl platform.  :-(

Cheers,
Chris

**Comment by mohawk2** [comment]
I propose this organisation scheme:

Any team member can make a branch, and PR it. Pumpking (someone who is able to be fairly responsive) can say "yea or nay", but after 7 days it's assumed to be a "yea" and the team member may merge - exception if there is violent discussion still ongoing. I propose this **NOT** be further formalised: no more bureaucracy.

Thoughts?

**Comment by plicease** [comment]
I would back @mohawk2's proposal as a way to at least reverse the stall on AB development.  Caveat being that I am fine with the bureaucracy if those that back it invest the time in making it work.

I also agree with @devel-chm in that I feel that some of the issues are design/systemic and are going to be difficult to address without starting from scratch.  That shouldn't prevent work on AB from going forward; an "Alien2" (or Alien::Install, a concept I have been tinkering with) can still be developed simultaneously and whether "Alien2" takes over or if AB borrows ideas from "Alien2" where appropriate it doesn't really matter so long as the overall Alien ecosystems improves.

Another thing to consider is that the useful set of modules that depend on AB is small enough that perhaps AB developers shouldn't be afraid of breaking compatibility, if consensus is reached, it improves the overall Alien ecosystem and AB developers coordinate with authors of existing AB dists.  AB is much much smaller than infrastructure projects like MakeMaker and Module::Build, and I think it is still at the "more important to get it right" than "maintain backwards compatibility" stage.

**Comment by mohawk2** [comment]
I propose that if in 7 days (by 23:59 UTC on 6 Sep), none of the honchos here have objected, that my proposal become the way things are done here. Obviously, they might all weigh in with assent before then.

Seems like the alternative is pretty much just more "nothing". That would be a real shame.

**Comment by jberger** [comment]
As I have said before, I want to see AB continue and even to be better than what I have written. Certainly I want it to be less unix-centric and I have always wanted (indeed I begged) for help on making it more flexible. My problem now is that I have neither the time nor the motivation to work on it. That is why I started giving up the reigns to begin with. I tried to copy the policy from Mojo because I knew it worked for us. I did not intend it to hamper development further. 

Normally for inclusion to the project, mostly I want to see some PRs submitted. That said, since it seems that there are several PRs waiting, and I truly don't know what the right thing to do with regards to them, what I really need is someone with the gumption to evaluate and merge PRs and from there we can all work to improve things. This means that I cannot simply rely on providing PRs as my guidance choice.

@plicease I haven't started an issue to have you added, however, you are arguably the most familiar with the issues the project has as you have actually worked your way around them.

I haven't heard actual votes from the other core members privately, and what I need is the energy from the new blood, I'm going to simply do the following. 
- I'm going to give commit bits to all three enthusiastic members. Please take the privilege seriously, please don't make me have to wield any hammers. 
- I'm going to clarify the rules for voting to be secret ballot with a time-frame, with time-elapsed votes counting as being an abstention.

Let's make AB what I had hoped it would be, a tool worthy of CPAN.

**Comment by devel-chm** [comment]
I do think that some structural changes will need to optimize
AB for Alien2 capabilities however, the fact that it is a build-on
framework means that we can make the changes and fairly
simply port existing AB users to A2B.  For most purposes, I
hope that the "fixed" API still starts from the same beginnings.
It just works a lot better making things work cross-platform.

Here are some of the pieces we have (already!) to work with.
This is a list of my thoughts which may differ from others
ideas along the same lines:

(1) Use PkgConfig to standardize communication of platform
     installation information and capabilities.  NOTE: we will
     need to deal with issues of whether and where the pkg-config
     files would be but it makes sense to me that the vocabulary
     should still be the same whether or not a distribution pkg-config
     is present.

(2) AB is improving incrementally but I think a simple refactoring
     to make the operation symmetric across platforms would
     really help

(3) I think we should think about using EUMM as the dominant
     build process for AB (vs MB) for a number of reasons.  EUMM
     is the defacto build process for perl and is supported across
     ALL perl platforms.  Many/all external dependencies actually
     need the usual make/gcc/... environment to build so a AB
     module would need a make, a shell, and a compile environment
     to do more than detect.  We could support a set of MB tools
     or modules to enable platform users to obtain a make+shell+cc
     build environment and then go straight make from there.
     Personally, I think the pure perl build tool is the most elegant
     solution but MB seems to be losing momentum---in part
     because it is a thankless job to implement EUMM _and_ make
     in perl.  Lots of more enjoyable and interesting things to program
     out there!

(4) PDL has a large number of external dependencies that could
     be used as use cases with which to develop this functionality
     along with a number of motivated developers.

Cheers,
Chris

**Comment by mohawk2** [comment]
I'm opening a new issue, and I'll c+p @devel-chm's excellent remarks above and then respond.

**Comment by MidLifeXis** [comment]
In light of this thread, I do agree with @plicease in that there seems to be limited time to devote to this project from some members, myself included.  That being said, I am eager to see this project move ahead, as I use quite a few items that would fall into the alien category.  For the good of the progress of this community, I am going to withdraw myself from the core development team.

When I find an itch in need of scratching and the time to implement, expect a fork/pull request.  Otherwise, I am a hindrance to the forward progress.  Keep up with this project - I love the concept and what it has the potential of providing.

**Comment by mohawk2** [comment]
I think the situation is a shame, but I applaud your commitment to the project, and look forward to any issues or PRs!
